#!/bin/sh

VCFFILE="/erdos/shokin/NCBI/VCF/AREDS/Affy_gru_merge.vcf"
SNPBATCHFILES="/erdos/shokin/NCBI/snpBatch/snpBatch_AFFY_33750,/erdos/shokin/NCBI/snpBatch/snpBatch_AFFY_33751"
OUTFILE="/erdos/shokin/NCBI/VCF/AREDS/Affy_gru_merge-GRCh38.vcf"

#VCFFILE="/erdos/shokin/NCBI/VCF/AREDS/Illumina_gru_merge.vcf"
#SNPBATCHFILES="/erdos/shokin/NCBI/snpBatch/snpBatch_ILLUMINA_33668"
#OUTFILE="/erdos/shokin/NCBI/VCF/AREDS/Illumina_gru_merge-GRCh38.vcf"

java -server -cp "build/install/gwas/lib/*" org.ncgr.gwas.SNPLifter $VCFFILE $SNPBATCHFILES > $OUTFILE 
